name = input("Enter your name: ")
age = input("Enter your age: ")
height = float(input("Enter your height (in meter): "))
weight = float(input("Enter your weight (in kg): "))
bmi = weight / (height ** 2)
print("Your BMI is: ",bmi)